apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/mennakamel25/Micro-Service-Project
    targetRevision: main
    path: helm/otel-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
