name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Test
        run: |
          cd src/product-catalog
          go test ./...

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: AWS login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        run: |
          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/product-catalog:${{ github.run_number }}

          docker build -t $IMAGE src/product-catalog
          docker push $IMAGE

  update-manifest:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update image tag
        run: |
          sed -i "s|image: .*|image: $IMAGE|" kubernetes/productcatalog/deploy.yaml

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "update image tag"
          git push