name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - accounting
          - cart
          - currency
          - flagd-ui
          - fraud-detection
          - product-catalog
          - image-provider
          - load-generator
          - checkout
          - payment
          - shipping
          - recommendation
          - frontend
          - frontend-proxy
          - email
          - ad

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ matrix.service }}:${{ github.run_number }}

          docker build \
            -t $IMAGE \
            ./src/${{ matrix.service }}

      - name: Push Docker image
        run: |
          IMAGE=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ matrix.service }}:${{ github.run_number }}

          docker push $IMAGE